### ISSUE TITLE
Please provide a minimal image of Gentoo-on-B3  

### ISSUE THREAD

**Issue by spitfire** [sakaki-/gentoo-on-b3#2]
I'd like to have a more lightweight image of your 'distro', containing just the required ebuilds + B3-specific tools, but no multimedia packages. A B3-specific stage3 image would also be useful. I want to run different applications in separate lxc containers. Could you publish such images?

**Comment by sakaki-** [comment]
Both would be possible, I guess. What sort of networking setup would be acceptable / useful for the lightweight bootable image (as the current full image uses shorewall, dnsmasq etc., and I'm guessing you wouldn't want that)? Also, if you could have a look at the current installed package list ([here](https://github.com/sakaki-/gentoo-on-b3/blob/master/reference/installed-packages)) and let me know specifically what (non @system-) packages you'd be happy to lose, that'd be useful.

**Comment by spitfire** [comment]
Hi,

I guess DHCP on the WAN interface would work fine.

The following packages (if not already part of stage3/@system) could be useful:

app-admin/sudo-1.8.12
app-admin/syslog-ng-3.6.4
app-misc/screen-4.3.1-r1
app-portage/eix-0.30.11
app-portage/euses-2.5.9
app-portage/gentoolkit-0.3.0.9-r2
app-portage/genup-1.0.9
app-portage/layman-2.0.0-r3
app-portage/mirrorselect-2.2.2-r2
app-portage/portage-utils-0.56
app-portage/showem-1.0.1-r1
app-shells/bash-4.3_p39
dev-libs/lzo-2.09
dev-vcs/git-2.4.10
net-dns/dnsmasq-2.72-r2
net-misc/rsync-3.1.1
net-misc/wget-1.16.3-r1
sys-apps/b3-init-scripts-1.0.5
sys-apps/gentoo-functions-0.10
sys-power/bubba-buttond-1.4-r3

Do you  have any instructions that would help with compiling/configuring gentoo on B3?

**Comment by sakaki-** [comment]
Ok, I'll have a look at that over the weekend. Just to check - the lightweight image is straightforward enough, but by "stage3", you mean a root system tarball without any kernel or kernel modules, nothing in /usr/portage/distfiles, an empty eix cache, but otherwise configured correctly for the B3, yes?

_wrt_ dev hints, as with any modest-capacity embedded system, getting a usable cross-compilation toolchain is probably the most important thing to sort out early on. I have a short guide on this project's wiki about that [here](https://github.com/sakaki-/gentoo-on-b3/wiki/Set-Up-Your-Gentoo-PC-for-Cross-Compilation-with-crossdev). I recommend setting up `distcc` as well as `crossdev` (both are covered in the wiki guide), as there are many packages where a pure cross-emerge on the PC does not work - due to issues with `./configure` returning information about the wrong target etc. - but where `distcc` still works, and speeds things up considerably. You should be able to get a `distcc` client running in a container, as long as it has IP connectivity your `distcc` server PC(s).

**Comment by spitfire** [comment]
Yep, I am planning to run a 'lightweight' base system, and run lxc containers (which don't need a compiled kernel, hence the stage3) on top of it. I should be able to build everything starting from a armv5tel stage3, right?

**Comment by sakaki-** [comment]
OK, please have a look at the files `genb3img-lite.xz` and `stage3-lite.xz` in [release 1.8.0](https://github.com/sakaki-/gentoo-on-b3/releases); hopefully pretty close to what you want. I ended up leaving the following in @world:

```
app-admin/logrotate
app-admin/sudo
app-admin/syslog-ng
app-misc/screen
app-portage/eix
app-portage/euses
app-portage/gentoolkit
app-portage/genup
app-portage/layman
app-portage/mirrorselect
app-portage/portage-utils
app-portage/showem
dev-embedded/u-boot-tools
net-dns/dnsmasq
net-firewall/iptables
net-misc/bridge-utils
net-misc/dhcpcd
net-misc/openssh
sys-apps/b3-init-scripts
sys-apps/ethtool
sys-apps/haveged
sys-apps/mlocate
sys-devel/distcc
sys-devel/gcc
sys-fs/dosfstools
sys-fs/mtd-utils
sys-kernel/buildkernel-b3
sys-libs/e2fsprogs-libs
sys-power/bubba-buttond
sys-process/cronie
sys-process/lsof
```

Feel free to pare these back further if required  (incidentally, I left `gcc` in there because it's such a time sink to install from source, as you can't `distcc` it due to the bootstrap). The stage 3 is basically a root tarball of this same image, minus kernel and kernel modules.  As you note, you could also use a vanilla `armv5tel` stage 3 in a `chroot`.

The minimal image has no WiFi configured. It brings up a DHCP server on the LAN port (B3 address 192.168.50.1) (log in via this interface), and looks for (but does not require) a DHCP server (i.e., your ADSL router or similar) connected to the WAN port for external Internet access. No forwarding between LAN and WAN ports is initially configured. The root password remains `gentoob3`.

**Comment by spitfire** [comment]
Thanks a lot for the info!
I have one question - have you tried running it on btrfs?

**Comment by sakaki-** [comment]
I haven't tried btrfs on the B3, but others have ([on my Archlinux image](http://forum.excito.com/viewtopic.php?p=27416#p27416), for example). It is configured as a module in the Gentoo B3 image's kernel, so you should be able to try it out.

**Comment by spitfire** [comment]
I have tried booting with the following config:
CONFIG_BTRFS_FS=y
CONFIG_CMDLINE="root=PARTUUID=13ff39a2-066d-4bf3-b8a4-473737fa9fc2 rootfstype=btrfs rootflags=subvol=root rootdelay=5 console=ttyS0,115200n8 earlyprintk" (I have my system on a subvolume called 'root')

There is a configuration item called "CONFIG_CMDLINE_EXTEND" which controls how "CONFIG_CMDLINE" parameters are passed. Do you know if there is any other way to change these parameters without recompiling the kernel every time?

**Comment by sakaki-** [comment]
You could use `kexec` (that is what I do in my Archlinux image, see [here](https://github.com/sakaki-/archlinux-on-b3/blob/master/reference/initramfs-init-live-usb) and [here](https://github.com/sakaki-/archlinux-on-b3/blob/master/reference/kexec-on-live-usb.sh)), or (_at your own risk_) change the command line in U-boot's flash environment, and use that (I needed a different command line to U-boot's default for the image, but, since I didn't want to require users to have to flash anything (to avoid the risk of less experienced bricking their device), I used a hardcoded command line). `dev-embedded/u-boot-tools` is included in the Gentoo image (and the minimal image too).

**Comment by sakaki-** [comment]
Closing this, as the minimal image (and stage3) was provided, as requested in the original issue.
